### ISSUE TITLE
Any plan to integrate the Repository Activity Score pattern?

### ISSUE THREAD

**Issue by 3cpt** [zkoppert/innersource-crawler#17]
Hi. Do you have plans to integrate the [Repository Activity Score](https://patterns.innersourcecommons.org/p/repository-activity-score) pattern? Or do you think that is out of the scope of the project?

I could help you if you want to move forward with that.

**Comment by 3cpt** [comment]
InnerSourceCommons/InnerSourcePatterns#341

**Comment by 3cpt** [comment]
> @3cpt Are there changes in this repository you would like to make or is the work completed by [InnerSourceCommons/InnerSourcePatterns#341](https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/341) ?

I'm finishing the Python implementation of the `Repository Activity Score` and I hope to have time to integrate it until the end of the month.
I need to think if I integrate it via package or directly because I probably will need to integrate it in other projects. 
It is ok to you, or you prefer not add more dependencies? You can always reject the PR. 😄

**Comment by spier** [comment]
just a quick status update. Work on the implementation of the repo activity score is continuing in here:
https://github.com/InnerSourceCommons/repo-activity-score
